### ISSUE TITLE
[request] Query Discord server

### ISSUE THREAD

**Issue by xLeviNx** [tltneon/lgsl#10]
Not sure if it is possible, but to be able to query the discord server. I have seen some forums/websites that have live info on the channels, users, etc

**Comment by tltneon** [comment]
It is possible but unlike LGSL uses different way to get data.

**Comment by xLeviNx** [comment]
Thanks for adding this feature. I noticed that users cannot click on the discord (server id) to connect to it, rather it automatically directs them to the official discord website. Is there a way you can implement comments for us to add so they can redirect themselves to the discord server?

**Comment by tltneon** [comment]
For now I'm searching a easy way to add that feature.  I'll looking into for adding this feature without any global changes in code

**Comment by tltneon** [comment]
There is a strange way but it works with minimal changes. For example:
To add Discord insert into IP next string - **130030068377452544.dayz** , where:

- "**130030068377452544**" is server id
- "**dayz**" is invite code from link https://discord.com/invite/dayz

And be sure you're add dot (.) symbol between id and code

**Comment by xLeviNx** [comment]
> There is a strange way but it works with minimal changes. For example:
> To add Discord insert into IP next string - **130030068377452544.dayz** , where:
> 
> * "**130030068377452544**" is server id
> * "**dayz**" is invite code from link https://discord.com/invite/dayz
> 
> And be sure you're add dot (.) symbol between id and code

Works great. Is there a way we can edit the string where the server ID is and just display the invite link?

![image](https://user-images.githubusercontent.com/48465241/86140852-53764080-babf-11ea-870e-851d90e4ec9f.png)

So instead of 192153663555371008.W​PzuMUV​:1 it says https://discord.gg/WPzuMUV

**Comment by tltneon** [comment]
@xLeviNx It's been a while, hah. Now discord link shows as you suggested.
Also you don't need to add server's ID - only place invite code W​PzuMUV as IP.

**Comment by xLeviNx** [comment]
Just updated to the new edition, and whenever I input the invite code as the IP, it resets and just pastes the W, and auto disables the server.
