### ISSUE TITLE
query live function problem with fetching data in cycle

### ISSUE THREAD

**Issue by Pok4** [tltneon/lgsl#103]
Hi guys,

I have a little problem with query live function (lgsl_query_live), i added few servers and they are in while cycle, i have this:

```
$get_servers = $dbh->query("SELECT * FROM ".getenv('DB_PREFIX')."greyfish_servers WHERE `gtrs`='0'");
		while ($row = $get_servers->fetch(PDO::FETCH_ASSOC)) {
			$server_ip = $row['ip'];
			$server_port = $row['port'];
			$server_type = $row['type'];
			$servid = $row['id'];
			
			//Query by Type
			switch ($server_type) {

			case  'cs16': {
					$result = lgsl_query_live('halflife', ''.$server_ip.'',  $server_port, $server_port, 0, "s");
					if (!isset($result['b']['status'])) {
						//offline
						$query_q_cs = $dbh->query("UPDATE ".getenv('DB_PREFIX')."greyfish_servers SET status='0', players='0',maxplayers='0' WHERE id='$servid'");
					} else {
						//online
						$host_cron = iconv('UTF-8', 'ISO-8859-1//TRANSLIT//IGNORE', $result['s']['name']);
						$map_cron = $result['s']['map'];
						$p_cron = $result['s']['players'];
						$maxp_cron = $result['s']['playersmax'];
						$dbh->query("UPDATE ".getenv('DB_PREFIX')."greyfish_servers SET status='1',hostname='$host_cron',map='$map_cron', players='$p_cron',maxplayers='$maxp_cron' WHERE id='$servid'");
					}
					break;
				}

			case 'csgo': {
					$result = lgsl_query_live('halflife', ''.$server_ip.'',  $server_port, $server_port, 0, "s");
					if (!isset($result['b']['status'])) {
						//offline
						$query_q_cs = $dbh->query("UPDATE ".getenv('DB_PREFIX')."greyfish_servers SET status='0', players='0',maxplayers='0' WHERE id='$servid'");
					} else {
						//online
						$host_cron = iconv('UTF-8', 'ISO-8859-1//TRANSLIT//IGNORE', $result['s']['name']);
						$map_cron = $result['s']['map'];
						$p_cron = $result['s']['players'];
						$maxp_cron = $result['s']['playersmax'];
						$dbh->query("UPDATE ".getenv('DB_PREFIX')."greyfish_servers SET status='1',hostname='$host_cron',map='$map_cron', players='$p_cron',maxplayers='$maxp_cron' WHERE id='$servid'");
					}
					break;
				}
```

the servers is from gametracker, current list:
https://ibb.co/cYG0xM5

Sometimes  servers is not querying properly (hostname and players/maxplayers).

I use phpfastcache and set it to 300 (seconds). All servers is updating on 300 seconds. But when this 300 seconds expire, all fetching starting again and  query live function started again, and again, and again for all servers because while cycle.
Maybe its need more time to fetch properly all servers.. Can you test it more servers (in cycle) with this function ?

Sometimes servers are properly fetching the data, but sometimes not. When i add servers from admin panel everything is ok, but this while cycle maybe kill all querying when started to using live function on and on...

Can you give me advice - what to do ?

**Comment by Pok4** [comment]
It happens most often with samp/minecraft and ts3.

**Comment by Pok4** [comment]
I'm wondering about curl vs fsockopen method... Which is default for live function? And can be changed?

**Comment by Pok4** [comment]
i try to use sleep function on every case in while cycle but without success. I set sleep(3).
The script run slowly with this type of function, but nothing change... Maybe the problem is in query live function ?

**Comment by TacTicTow** [comment]
Change the end of your $result line and query everything to see if that makes a diiference. 

change

$result = lgsl_query_live('halflife', ''.$server_ip.'',  $server_port, $server_port, 0, "s");

to

$result = lgsl_query_live('halflife', ''.$server_ip.'',  $server_port, $server_port, 0, "sep");

**Comment by Pok4** [comment]
i try but without success... It works on same way..

**Comment by Pok4** [comment]
Here is a pic: https://i.ibb.co/p4hPCxQ/ss.png

**Comment by TacTicTow** [comment]
Odd: I have always used the class file to read my servers. For example.

<?php
  include(../lgsl/lgsl_files/lgsl_class.php');
  $result = lgsl_query_live('callofduty4', '64.74.97.92', 28960, 28960, 0, "sep");
  print_r($result);  // there is will be an array of result of querying
?>

Just for the hell of it, try it and let me know if it makes a difference.

Change:

include(__DIR__.'/vendor/tltneon/lgsl/lgsl_files/lgsl_protocol.php');

To:

include(__DIR__.'/vendor/tltneon/lgsl/lgsl_files/lgsl_class.php');

**Comment by Pok4** [comment]
Nothing change. Maybe the problem is in query_live function...
The strange thing is that the servers is not marked as offline, the status is not show the players and the hostname.
The "offline" text not appear...

**Comment by tltneon** [comment]
Hello @Pok4 

Status sets to "offline" cause gets no certain data from server. It maybe be timeout if server didn't respond. Or just gets wrong packet data (if server can send several packets). Or because exceeded php max execution time

I'll test your code and find why it happens.

**Comment by Pok4** [comment]
I'm waiting for your response :)

**Comment by tltneon** [comment]
So I testing your code and looking how it works.

**Minecraft** protocol works good with some servers - maybe protocol has changes in different MC versions. Need to look deeper..
![image](https://user-images.githubusercontent.com/2452201/163126903-145cc62b-8be8-4eb8-afbf-ec7849755f0d.png)


**SAMP** sometimes just not to send packet :unamused: 
![image](https://user-images.githubusercontent.com/2452201/163124782-69d48eb1-f92d-4f4f-a3aa-27d7d41a554f.png)
- it can be fixed with additional sending query (I add it next commit) or **$lgsl_config['retry_offline'] = true** can be useful in this case.

And **TS3** is clock-work. I can't connect to your server but two random servers works.
![image](https://user-images.githubusercontent.com/2452201/163123274-a363777d-5396-474d-bada-6a3dd48faeea.png)

**Comment by Pok4** [comment]
i see sometimes in random servers (cs 1.6), the players not showing from first click. When i click on the players tab second time - they shows.
Maybe something is changed ... 

$lgsl_config['retry_offline'] - can this works with lgsl query live function or only in lgsl_class ?

Thank  you for your time, i know that this stuff is boring, but anyway, you are the guy :)

**Comment by tltneon** [comment]
Players data and server data sended in different packets for 1.6 so there is nothing odd that sometimes players not showing. Its just loads next time

$lgsl_config['retry_offline'] works only in lgsl_class. If you don't want to use lgsl_class you need to make something like:
```php
      $server = lgsl_query_live($type, $ip, $c_port, $q_port, $s_port, "sep");

      if (!$server ['b']['status'])
      {
        $server = lgsl_query_live($type, $ip, $c_port, $q_port, $s_port, "sep");
      }
```
