### ISSUE TITLE
Query for Project Zomboid

### ISSUE THREAD

**Issue by BaxAndrei** [tltneon/lgsl#108]
Hi. Would it be possible to add query for Project Zomboid?

I hope this helps: https://pzwiki.net/wiki/Dedicated_Server https://www.battlemetrics.com/servers/zomboid

Thank You.

**Comment by tltneon** [comment]
Hi, @BaxAndrei 

PZ already works good on Source protocol
https://github.com/tltneon/lgsl/wiki/Supported-Games,-Query-protocols,-Default-ports

**Comment by BaxAndrei** [comment]
It works perfectly, thank you. I didn't see it in the list when I wanted to add the server. Then I looked on the wiki. Thanks.
