### ISSUE TITLE
How

### ISSUE THREAD

**Issue by HaaArllLoWWW** [tltneon/lgsl#11]
![image](https://user-images.githubusercontent.com/35719796/81572845-68323400-93ac-11ea-9da5-938afdb5d1fd.png)
How to add monitor to forum ?

**Comment by xLeviNx** [comment]
You can try requiring the index file on the website, and test it. 


`<?php
	require "lgsl_files/index.php";
?>`

Haven't tested it but should work

**Comment by HaaArllLoWWW** [comment]
i have installed and configured but i need code  upload in forum

**Comment by tltneon** [comment]
First of all, what the forum engine do you use? The simplest way is to add html or php block.
Html should be like 
<iframe src="lgsl_files/lgsl_list.php" width="100%" height="400px"></iframe>
And php like 
<?php require "lgsl_files/lgsl_list.php"; ?>

**Comment by Badman173** [comment]
hello @tltneon  i installed it on a webhosting but my (csgo) servers are not responding, 
I talked to my supplier, but he said I need a vps for this, is there anything I can do?
sorry to bother you

**Comment by tltneon** [comment]
Hello, @Badman173 !
Most of paid webhosts allowed to use php's fsockopen function with udp protocol (for querying gameservers) and there is no need for vps. If your webhosting restricts that feature you can rest another cheap php webhost
