### ISSUE TITLE
Mordhau not giving info on query

### ISSUE THREAD

**Issue by Zorrototo** [tltneon/lgsl#116]
It seems like Mordhau server is not giving info on query anymore. First issue, now you need to enable a parameter `bAdvertiseServerViaSteam=True` in the server config, or else it doesn't reply to anything. But even then, with this parameter configured, LGSL doesn't seem to be able to get basic server info (no server name, no map info, no player info). 

Is anyone able to make a Mordhau game server, and query its info through LGSL? I can't. It works for any other game server so I think something changed between years ago when I first used it without issue, and now.

**Comment by tltneon** [comment]
@Zorrototo Hello! Can you get me your server's IP and query port? 
It need to look into packets that server sends

I tried some servers and some of it can be scanned, e.g.
![image](https://user-images.githubusercontent.com/2452201/168889630-498c6fdb-a1d0-4397-a069-a2b8eabd46cc.png)

**Comment by Zorrototo** [comment]
For example this server https://www.battlemetrics.com/servers/mordhau/15244094
```
188.40.99.242:7452 (Game Port)
188.40.99.242:26690 (Query Port)
```
What is weird is a website like Battlemetrics can see the server but I can't with LGSL.
It is a Linux server if that makes a difference.

**Comment by tltneon** [comment]
Also works
![image](https://user-images.githubusercontent.com/2452201/168973055-960a9077-680f-45a7-9d33-cde7e8778241.png)

Be sure that LGSL has ability to query server
![image](https://user-images.githubusercontent.com/2452201/168973308-a238c7e3-cfc7-446e-9c16-fdd138c5c398.png)
![image](https://user-images.githubusercontent.com/2452201/168973373-62afce7e-2bdc-4fdc-bfdc-1c7c16e01476.png)

**Comment by Zorrototo** [comment]
OK then I will have to find what's going on on my side. Thanks for testing.

**Comment by Zorrototo** [comment]
Issue was my mistake I was missing a piece of code for the challenge thing added not so long ago in the source query protocol.
