### ISSUE TITLE
status NO RESPONSE

### ISSUE THREAD

**Issue by obteo** [tltneon/lgsl#119]
Hello, seems i cannot have the net status online even if server is online :/
Game = sof2 
VPS provider: OVH 
OS: ubuntu 18.04
LGSL stand alone on a shared hosting OVH plan

any idea please?

**Comment by tltneon** [comment]
Hello, @obteo !
At first, be sure that your web hosting allows to send udp packets and server hosting has port forwarding.

And it will be handy if you write down your ip and query port

**Comment by obteo** [comment]
Hello, tried moving to a new VPS, now web hosting is OVH and VPS is nfoservers, same story... I will ask to web hosting provider if they allow sending UDP packets. The game server IP is: 185.107.96.142:20200

Thank you.

**Comment by obteo** [comment]
Is something with the panel, they told me it allows UDP...

http://cp.youngandoldboys.com/phpinfo.php

**Comment by tltneon** [comment]
Hmm... works fine for me

![image](https://user-images.githubusercontent.com/2452201/176926470-013078db-1204-4e2a-b97f-96e2d6ad17b5.png)

Looks like your LGSL can't dig server's data

**Comment by obteo** [comment]
Thank you for testing, how can I fix it please?

**Comment by tltneon** [comment]
If your admin panel the same

![image](https://user-images.githubusercontent.com/2452201/176929916-9a5f5371-f5b0-43eb-9adb-41b4023b8cba.png)

try to query any other servers (cs 1.6, samp, minecraft). If they has "no responce" status - contact hosting support cause is no packets came from server

**Comment by obteo** [comment]
as I wrote I have OVH shared hosting, the php info are into my previous post. Unfortunately I'm not allowed installing packages like when I had my own WHM server

**Comment by obteo** [comment]
hi yes is ther same: 
![image](https://user-images.githubusercontent.com/14107419/193575271-823e32a1-5df2-4951-8ba2-799a52e8236f.png)

can't understand why this.. you can try addin yourself here:
https://www.youngandoldboys.com/lgsl/
