### ISSUE TITLE
Add fiveM Support

### ISSUE THREAD

**Issue by BearGryllsTV** [tltneon/lgsl#12]
Hey, First of all I would like to say a massive thank you. Our admin team use this as a quick overview if the server 2nd. I was wondering you could add fiveM support. 

It should be pretty simple as they support is already in place, they have json files for each server you setup on the ip:port

http://54.37.244.192:30120/info.json
http://54.37.244.192:30120/players.json

**Comment by tltneon** [comment]
Appreciate you for that links it will be useful for adding fiveM support. And it possibly should be in few weeks or little earlier because I'm busy right now
