### ISSUE TITLE
site showing less servers than added

### ISSUE THREAD

**Issue by GameCSBR** [tltneon/lgsl#125]
Could you tell me why I have 34 servers added to the list but the site only shows 30?

List Show 30 Server : https://prnt.sc/jbm10cxswTls
Page Admin : https://prnt.sc/3XEeVP5953yC
My Web: https://servidores.gamecs.com.br/

**Comment by tltneon** [comment]
Hello @GameCSBR 

I guess you checked that checkbox when install LGSL
![image](https://user-images.githubusercontent.com/2452201/185759310-be501716-fe62-4a5a-adac-17758e63eab2.png)

Just write `$lgsl_config['hide_offline'][0] = 0;` in config to show all the servers.

**Comment by GameCSBR** [comment]
It's true, I checked that option. thanks for clearing my doubt
