### ISSUE TITLE
Port CS 1.6

### ISSUE THREAD

**Issue by GameCSBR** [tltneon/lgsl#126]
would there be any way to accept counter strikr 1.6 servers with ports greater than 28000?

**Comment by BaxAndrei** [comment]
I see that the maximum possible port is set to 65536

**Comment by GameCSBR** [comment]
more I try to add a server with port 28000 it does not accept

**Comment by BaxAndrei** [comment]
Any log or error (ss)?

**Comment by GameCSBR** [comment]
Link Error: https://prnt.sc/XE-NCi-JgY6r


NO ANSWER - Make sure you have entered the correct details.

**Comment by BaxAndrei** [comment]
![image](https://user-images.githubusercontent.com/12484505/186268859-b4bcd844-2b16-4ce1-b1d1-6906867582e8.png)
Server is online right now? You can join it?

**Comment by GameCSBR** [comment]
yes, the servers are online.
https://prnt.sc/BlepG0WlXONC
