### ISSUE TITLE
Unable to add the server 

### ISSUE THREAD

**Issue by BerserkRO** [tltneon/lgsl#128]
I have added this type of server
![ser](https://user-images.githubusercontent.com/112158702/186848217-c038a15d-06b8-4167-b2ed-63a25d4a73cb.png)

But i still get the the result below 
![serv](https://user-images.githubusercontent.com/112158702/186848449-d33823c4-b908-41ae-b7b5-a4de5fa62d3f.png)

Can someone help me please

**Comment by tltneon** [comment]
Hello @BerserkRO 
You need to be sure that your server is online and has opened ports; also check you write correct query port and your hosting provider allows you to  use fsockopen function (see in admin)
