### ISSUE TITLE
Rage:MP add LGSL

### ISSUE THREAD

**Issue by easyway-icore** [tltneon/lgsl#13]
You can add ragemp?

**Comment by tltneon** [comment]
I looked for the ways to add Rage:MP support into LGSL and yes I can make something for fetching servers status

**Comment by easyway-icore** [comment]
> I looked for the ways to add Rage:MP support into LGSL and yes I can make something for fetching servers status

I will be infinitely grateful! I hope you do not forget about Rage:MP
