### ISSUE TITLE
Server dependency

### ISSUE THREAD

**Issue by kitaroar** [tltneon/lgsl#135]
I installed lgsl 6.2.0 on 3 different hosting company for testing. Two on vps server with Ubuntu 22.04 and Hestia Cpanel. One on shared hosting.
These 3 websites give me three different results with same config file and same servers on the list.

All the servers are online and I can connect and play on them.

On all 3 pages, on admin page it says I have all the modules needed.

![Screenshot_1](https://user-images.githubusercontent.com/31425662/192142563-a19a8670-089e-4875-80d3-84a2350d3da0.png)
![Screenshot_2](https://user-images.githubusercontent.com/31425662/192142570-9f52d999-8e6c-456f-80d1-3b9aebd4811b.png)

What I have to do to show the servers online on every location I install lgsl? There are some other dependency needed to be installed on the server?

Thanks.

**Comment by tltneon** [comment]
Nothing else is needed.
But some hosting may disallow to use fsockopen by users. Or just block UDP/TCP querying. So that's cause you to can't query a data from servers by UDP protocols (such as this cs 1.6 servers) and TCP protocols on that hostings.
