### ISSUE TITLE
Add support: Eco

### ISSUE THREAD

**Issue by RockyRavenheart** [tltneon/lgsl#137]
Please add support for Eco, since a lot of things today start with the same phrase as the game title, below is the link to the game in mention.

https://store.steampowered.com/app/382310/Eco/

Hope you have a great day!

**Comment by RockyRavenheart** [comment]
I changed the request since support for space engineers was already available through source protocol.
It seems to ignore set query port, so connection port and query port are the same.

**Comment by tltneon** [comment]
Hi @RockyRavenheart
Just added support for Eco. Eco server's query port is connection port + 1
![image](https://user-images.githubusercontent.com/2452201/235256067-05620312-9774-459e-829a-cefcb7f04a64.png)
