### ISSUE TITLE
Userbar Error 500

### ISSUE THREAD

**Issue by LuckyTrixx** [tltneon/lgsl#142]
Hay,
Awesome Project and works very well.
Except for the userbars.

The bars simply wont work, checking the Browser console, i get an 500 Error and Opening the Bars directly in the browser, shows, that they can't be displayed, because they have errors.

Maybe someone here can help me.

Thanks in advance

**Comment by BaxAndrei** [comment]
Do you have GD/GD2/ImageMagick extension enabled?

**Comment by LuckyTrixx** [comment]
Hay, Thank you for your Answer.
Yes, i have GD enabled. here is a Screenshot of the Add-on Section of the Admin-Panel
![grafik](https://user-images.githubusercontent.com/19686899/208164962-cf288719-451b-43a3-85a6-85313adc92cb.png)

**Comment by BaxAndrei** [comment]
Do you have any error logs?

**Comment by LuckyTrixx** [comment]
Yes!
```[Sun Dec 18 14:59:28.443566 2022] [php:error] [pid 18] [client 172.19.0.2:52396] PHP Fatal error:  Uncaught Error: Call to undefined function imagettftext() in /var/www/html/lgsl/userbar.php:208\nStack trace:\n#0 {main}\n  thrown in /var/www/html/lgsl/userbar.php on line 208```

**Comment by BaxAndrei** [comment]
This might help: https://stackoverflow.com/a/7290973/3578614

**Comment by BaxAndrei** [comment]
Did you managed to fix it @LuckyTrixx ?

**Comment by LuckyTrixx** [comment]
Hay, partially. i activated FreeType and now 2 out of 3 of these Bars are Working. So, that is a Win in my Book. I am still figuring out, how to fix the last one.

**Comment by BaxAndrei** [comment]
Try to clear all erorr logs then show me what do you get now

**Comment by BaxAndrei** [comment]
Try to clear all error logs then show me what do you get now
