### ISSUE TITLE
Query For Euro Truck Simulator 2 / American Truck Simulator?

### ISSUE THREAD

**Issue by Sebbabas** [tltneon/lgsl#145]
Hello,
Would it be possible to add the Euro Truck Simulator 2 / American Truck Simulator Game?
I tested with the 05 protocol, the number and name of the players in play is not displayed.
Thank you .

Serveur :
ETS2 => 163.172.80.245:27500 - Qport:27501
ATS   => 163.172.80.245:27110 - Qport:27111

**Comment by BaxAndrei** [comment]
Do you have more details about the dedicated server (preferably official documentation)? I don't remember there being dedicated servers in ETS2, other than the convoys.

**Comment by Sebbabas** [comment]
Hello,
Doc => https://modding.scssoft.com/wiki/Documentation/Tools/Dedicated_Server.

**Comment by tltneon** [comment]
Works good but player names isn't sends by server
![image](https://user-images.githubusercontent.com/2452201/235134897-19cbe039-b090-4f0a-8946-060ce9cce7be.png)
