### ISSUE TITLE
Details Explain

### ISSUE THREAD

**Issue by KristianP26** [tltneon/lgsl#15]
Hello
can you please explain me which data i can get from details also how or how it works.

Because i am just able to get name, time and score.
Thanks.

**Comment by KristianP26** [comment]
I need to get SteamID and remove bots.

**Comment by tltneon** [comment]
Datas is differs from game to game. Some servers send you only player's name and frags. Some servers send you player's name and teams and ping and so on. Also works for all server's data.
If you want to know which datas the certain game sends, you need to read relative docs or explore retrieved data by yourself. For example: Source Query protocol https://developer.valvesoftware.com/wiki/Server_queries

**Comment by KristianP26** [comment]
Okay thanks, i figured out. I just can get from csgo servers username score and time and also player id on server but thats unseless.
