### ISSUE TITLE
timezone settings

### ISSUE THREAD

**Issue by papa3boyz** [tltneon/lgsl#150]
Warning: date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in D:\WebServers\USBWebserver\root\lgsl\lgsl_files\lgsl_list.php on line 50

I i fix this? My zone is Malaysia GMT+8 or Asia/Kuala Lumpur. TQ

**Comment by BaxAndrei** [comment]
You can just add `date_default_timezone_set("Europe/Bucharest");` after `<?php` in `lgsl_files/lgsl_config.php`. Here you find all timezones: https://www.php.net/manual/en/timezones.php . Hope this help you, for me it does it job.

**Comment by BaxAndrei** [comment]
`date_default_timezone_set("Asia/Kuala_Lumpur");`

**Comment by papa3boyz** [comment]
thanks it works

**Comment by BaxAndrei** [comment]
You are welcome!
