### ISSUE TITLE
userbar not refresh

### ISSUE THREAD

**Issue by j0ker977** [tltneon/lgsl#151]
Hello, why the userbar does not refresh, it saves the last data, if I do not enter the main lgsl page, the status will not change

**Comment by Sebbabas** [comment]
hello,
https://github.com/tltneon/lgsl/wiki#page-loads-slowly

**Comment by j0ker977** [comment]
curl --compressed -s -o /dev/null http://cs-strzelnica.pl/lgsl/lgsl_files/lgsl_cron.php not working
no error message but banners still not refreshing

php -q /var/www/html/lgsl/lgsl_files/lgsl_cron.php
error log:

PHP Warning:  Undefined array key "REMOTE_ADDR" in /var/www/html/lgsl/lgsl_files/lgsl_class.php on line 1063
PHP Warning:  Undefined array key "HTTP_HOST" in /var/www/html/lgsl/lgsl_files/lgsl_class.php on line 1006
PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/lgsl/lgsl_files/lgsl_class.php:113
Stack trace:
#0 /var/www/html/lgsl/lgsl_files/lgsl_cron.php(17): lgsl_database()
#1 {main}
  thrown in /var/www/html/lgsl/lgsl_files/lgsl_class.php on line 113

I don't know how to configure it :(
