### ISSUE TITLE
TS3 Loading Time

### ISSUE THREAD

**Issue by ZekyTheWolf** [tltneon/lgsl#157]
Hello there, i noticed that the query for TeamSpeka3 is taking actually pretty long... Almost up to 5 seconds, with is way too much.

In GameQ, took less / around 1 second... So, is there a possible optimization for TS3 Query?

**Comment by ZekyTheWolf** [comment]
I was able to optimize query for TeamSpeak 3 by removing TeaSpeak... [https://github.com/ZekyTheWolf/LGSQ/commit/ff36448567b70745117dbd73cafc59ea0c0c155f#diff-02a5b179ddc82fbde7e5c4c5fdfe099b14b596eb834c7e7d4e4a87fb517c0f13](commit)

From +/- 5 seconds i was able to get +/- 1 second (more test showed, less then 1 second).

So, i was thinking about creating seperate queries for TS/TS3 and TeaSpeak?

**Comment by ZekyTheWolf** [comment]
I was thinking about separating TeaSpeak and TeamSpeak query, but it shows up, it doesnt matter... Still up to 5 seconds...

**Comment by tltneon** [comment]
Have you tried sets the value lower than 3 seconds? Here https://github.com/tltneon/lgsl/blob/master/lgsl_files/lgsl_protocol.php#L669 and here https://github.com/tltneon/lgsl/blob/master/lgsl_files/lgsl_config.php#L138

**Comment by ZekyTheWolf** [comment]
> Have you tried sets the value lower than 3 seconds? Here https://github.com/tltneon/lgsl/blob/master/lgsl_files/lgsl_protocol.php#L669 and here https://github.com/tltneon/lgsl/blob/master/lgsl_files/lgsl_config.php#L138

Yep, that was it...

**Comment by ZekyTheWolf** [comment]
@tltneon what do you think about moving response to [Result.php](https://github.com/Austinb/GameQ/blob/v3/src/GameQ/Result.php) like in GameQ?

**Comment by ZekyTheWolf** [comment]
> Hmm, maybe it could make a point

It some ways it could, im currently testing it.

Still need to make few adjustments, but working great.

*Still not sure how much i can poke in code until it will be broken :D*

**Comment by ZekyTheWolf** [comment]
Code that use Result class looks much more clean... That is only benefit of it.
