### ISSUE TITLE
V7.0.0 - lgsl_protocol.php 

### ISSUE THREAD

**Issue by TacTicTow** [tltneon/lgsl#158]
Line# 507 has an error. This loop will continue on past the info queried causing an undefined key error. It happened when I tried to add a MW2 server with the 'callofdutyiw' protocol. 

$server['e'][$data_key] = $item[$item_key+1];

Replace line #507 with:

        if(isset($item[$item_key+1])) {         // check if the key exists
        $server['e'][$data_key] = $item[$item_key+1];
        }

It will now work. However there is still a bug I have not tracked down in the MW2 part of it. The script works now without errors, but all of the MW2 info is blank. It does not seem to pull data from the server. 

Our server is at 64.74.97.92:28961 if you wish to test. Going to attempt to debug this as well, but my php skills are not at your level. 

I have been tinkering with your code a bit to customize it. Added some game specific definitions, downloaded some high resolution icons, edited the server banner a bit (still working on it). Need to move bar graph and add the current map image. Almost there. 

If you wish to take a look. This is just a test server for me. I will use it on my live server once things are more stable. 

http://rsb.site.nfoservers.com/lgsl7/

Thank you for continuing to work on this script.

**Comment by ZekyTheWolf** [comment]
If you try replacing that part 
```
if(isset($item[$item_key+1])) {         // check if the key exists
    $server['e'][$data_key] = $item[$item_key+1];
}
```
with:
```
$s = 1;
if ($item[0]) $s = 0; // IW4 HAS NO EXTRA "\"

for ($i = $s; $i < count($item); $i += 2) { // SKIP EVEN KEYS
    $data_key               = strtolower(lgsl_parse_color($item[$i], "1"));
    $server['e'][$data_key] = lgsl_parse_color($item[$i+1], "1");
}
```
[source](https://github.com/tltneon/lgsl/blob/master/lgsl_files/lgsl_protocol.php#LL807C1-L814C1)

It should be working, 
![image](https://github.com/tltneon/lgsl/assets/99070546/3c10e4fe-324a-470d-9bbb-5e9d6635bab7)
(protocol: callofdutyiw)
