### ISSUE TITLE
Request to api.hellbz.de has changed

### ISSUE THREAD

**Issue by HellBz** [tltneon/lgsl#160]
Hello Admin,

please set the User-Agent to my API-Request like the following 

https://api.hellbz.de//scum/api.php?address=176.57.181.82&port=28700

With a New Formated and validated User-Agent in this Format

Bot-Name/Version (Author-Name; Author-Website; Author-Contact Website or E-Mail; Additional Informations)

For example:
SCUM-List-Crawler/1.0 (HellBz; https://hellbz.de; cofing@hellbz.de; Some more you like to tell me..)

Best Regards,

Stefan

**Comment by ZekyTheWolf** [comment]
[click](https://github.com/tltneon/lgsl/blob/master/lgsl_files/lgsl_protocol.php#L4040) isnt already new format active?

**Comment by HellBz** [comment]
You need to send a User-Agent with your Request.

  $agent = "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)";
  curl_setopt($curl, CURLOPT_USERAGENT, $agent);
  
  Yes, is already, but only with Generic Mozilla Firefox
  $http_send .= "User-Agent: Mozilla/5.0 (X11; U; Linux i686; en-GB; rv:1.9.1.4) Gecko/20091028\r\n";
  (https://github.com/tltneon/lgsl/blob/6add034535aa0ba8a52fd1f244fd7338b63e451d/lgsl_files/lgsl_protocol.php#L4364C9-L4364C108)

**Comment by ZekyTheWolf** [comment]
So... For now it will work, but for future better to change it?

**Comment by HellBz** [comment]
Its all fine, if is Mozillavdetected in User-Agent, it works.

For Better Traffic-Analytics it is better for me to See, wich script is Using my API, if you know, what I mean with this.

**Comment by tltneon** [comment]
Fixed in https://github.com/tltneon/lgsl/commit/6445d1e52afe2c5363ebff076978f93f4781d178
