### ISSUE TITLE
Discord and mumble not working !!

### ISSUE THREAD

**Issue by raymand211092** [tltneon/lgsl#161]
Used latest [commit](https://github.com/tltneon/lgsl/archive/master.zip)

I have tried port mumble 27800 for mumble plugin query and port 64738
And discord remains in REQUEST IN PROGRESS

**Comment by ZekyTheWolf** [comment]
Can you provide connection data for mumble and discord that you trying to use?

**Comment by ZekyTheWolf** [comment]
Just now tested discord/mumble and working without any problems.

**Comment by raymand211092** [comment]
> Can you provide connection data for mumble and discord that you trying to use?

mum.grupotd.nat.cu:64738
i tried with another server and if it worked..what should I activate to get my server out

My instance is https://lsdc.grupotd.nat.cu/

**Comment by ZekyTheWolf** [comment]
Do you have correct Connection Port and Query Port?

**Comment by tltneon** [comment]
Hello, @raymand211092 

Make sure that your mumble server has https://wiki.mumble.info/wiki/Channel_Viewer_Protocol
