### ISSUE TITLE
LGSL7: lgsl_protocol.php

### ISSUE THREAD

**Issue by Sirphr** [tltneon/lgsl#174]
`Warning :  Undefined array key "disabled_types" in /usr/www/sirphr/public/l4d.sbf.gg/lgsl_files/lgsl_protocol.php on line 328`
 
https://i.imgur.com/qUij6cj.jpeg

**Comment by tltneon** [comment]
Hello @Sirphr 
Can you say which commit are you using? It was fixed in ttps://github.com/tltneon/lgsl/commit/6cafdc46af65d7d30ad9c04063cc73ea3be10aa4

Try to reinstall LGSL (or just simply add ```$lgsl_config['disabled_types'] = false;``` in **lgsl_config.php**)

**Comment by BaxAndrei** [comment]
> `Warning : Undefined array key "disabled_types" in /usr/www/sirphr/public/l4d.sbf.gg/lgsl_files/lgsl_protocol.php on line 328`
> 
> https://i.imgur.com/qUij6cj.jpeg

You upgraded from latest release to lgsl7 branch?
