### ISSUE TITLE
LGSL7: mysqli_sql_exception

### ISSUE THREAD

**Issue by Sirphr** [tltneon/lgsl#175]
`Fatal error: Uncaught mysqli_sql_exception: Incorrect integer value: '' for column 'status' at row 1 in /usr/www/sirphr/public/l4d.sbf.gg/lgsl_files/lgsl_class.php:267 Stack trace: #0 /usr/www/sirphr/public/l4d.sbf.gg/lgsl_files/lgsl_class.php(267): mysqli->query() #1 /usr/www/sirphr/public/l4d.sbf.gg/lgsl_files/lgsl_class.php(254): tltneon\LGSL\Database->execute() #2 /usr/www/sirphr/public/l4d.sbf.gg/lgsl_files/lgsl_class.php(375): tltneon\LGSL\Database->query() #3 /usr/www/sirphr/public/l4d.sbf.gg/lgsl_files/lgsl_class.php(341): tltneon\LGSL\Database->lgsl_save_cache() #4 /usr/www/sirphr/public/l4d.sbf.gg/lgsl_files/lgsl_list.php(32): tltneon\LGSL\Database::get_servers_group() #5 /usr/www/sirphr/public/l4d.sbf.gg/index.php(50): require('...') #6 /usr/www/sirphr/public/l4d.sbf.gg/index.php(62): load_page() #7 {main} thrown in /usr/www/sirphr/public/l4d.sbf.gg/lgsl_files/lgsl_class.php on line 267`

**Comment by BaxAndrei** [comment]
> `Fatal error: Uncaught mysqli_sql_exception: Incorrect integer value: '' for column 'status' at row 1 in /usr/www/sirphr/public/l4d.sbf.gg/lgsl_files/lgsl_class.php:267 Stack trace: #0 /usr/www/sirphr/public/l4d.sbf.gg/lgsl_files/lgsl_class.php(267): mysqli->query() #1 /usr/www/sirphr/public/l4d.sbf.gg/lgsl_files/lgsl_class.php(254): tltneon\LGSL\Database->execute() #2 /usr/www/sirphr/public/l4d.sbf.gg/lgsl_files/lgsl_class.php(375): tltneon\LGSL\Database->query() #3 /usr/www/sirphr/public/l4d.sbf.gg/lgsl_files/lgsl_class.php(341): tltneon\LGSL\Database->lgsl_save_cache() #4 /usr/www/sirphr/public/l4d.sbf.gg/lgsl_files/lgsl_list.php(32): tltneon\LGSL\Database::get_servers_group() #5 /usr/www/sirphr/public/l4d.sbf.gg/index.php(50): require('...') #6 /usr/www/sirphr/public/l4d.sbf.gg/index.php(62): load_page() #7 {main} thrown in /usr/www/sirphr/public/l4d.sbf.gg/lgsl_files/lgsl_class.php on line 267`

You upgraded from latest release to lgsl7 branch? I had same issue, reinstall it and everything will work fine again.
