### ISSUE TITLE
Erro: lgsl_protocol

### ISSUE THREAD

**Issue by LKING1543** [tltneon/lgsl#179]
PHP Notice:  fwrite(): Send of 25 bytes failed with errno=1 Operation not permitted in /home1/clanre36/public_html/rank/lgsl/lgsl_files/lgsl_protocol.php on line 1133

Version LGSL: 6.2.0

I already gave permission 777 and nothing yet

**Comment by tltneon** [comment]
Hi @LKING1543 
Look that comment https://stackoverflow.com/a/12153349
