### ISSUE TITLE
Add VRising support

### ISSUE THREAD

**Issue by mohikan68** [tltneon/lgsl#184]
Please add support for VRising

https://store.steampowered.com/app/1604030/V_Rising/

**Comment by tltneon** [comment]
Hello, @mohikan68 
V Rising uses Source protocol so you can easily add your server even now
I'll add an icon for a better view
![image](https://github.com/tltneon/lgsl/assets/2452201/823825c0-6983-45a6-9ce2-b9ba04222d3a)

**Comment by mohikan68** [comment]
> Hello, @mohikan68 V Rising uses Source protocol so you can easily add your server even now I'll add an icon for a better view ![image](https://private-user-images.githubusercontent.com/2452201/295662301-823825c0-6983-45a6-9ce2-b9ba04222d3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MTE3ODQsIm5iZiI6MTcwNDkxMTQ4NCwicGF0aCI6Ii8yNDUyMjAxLzI5NTY2MjMwMS04MjM4MjVjMC02OTgzLTQ1YTYtOWNlMi1iOWJhMDQyMjJkM2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTBUMTgzMTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzdjNzk2YzY3M2NkNTM3YjBjNTk5NWQyNTNkMzg3ODkzNjM3NDFjYWZhNjMxYzM1ZTM2ODAxOWRkMGRjNWM0OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZZbtHMvSxa2vXYA2fMMAwh_e6Jb1lrC0UDwD6LGQQkI)

ty working
