### ISSUE TITLE
FiveM Issue: Undefined variable $server

### ISSUE THREAD

**Issue by wohahobg** [tltneon/lgsl#186]
Hi,

Today I tried to use FiveM type in LGSL v7 , but it give  Undefined variable $server;

in lgsl_protocol.php it's
```php
$this->_lgsl_fp->write("http://{$server['b']['ip']}:{$server['b']['q_port']}/dynamic.json");
```

but it should be something like that
```php
$serverIp = $this->_server->get_ip();
$serverPort = $this->_server->get_q_port();
$this->_lgsl_fp->write("http://{$serverIp}:{$serverPort}/dynamic.json");
```

**Comment by wohahobg** [comment]
Oh I just saw in source-code is alright 
https://github.com/tltneon/lgsl/blob/lgsl7/src/lgsl_protocol.php#L3392

look like i need to use dev version.

Feel free to close this.

**Comment by tltneon** [comment]
Hi, @wohahobg 
Thanks for activity :D
LGSL v7 more often gets updates rather than v6. I suggest to use latest commit of v7 but be aware of some errors

**Comment by wohahobg** [comment]
No worries!

I am planning to use this for our api.gamecms.org so yea if there is something will report it.
