### ISSUE TITLE
[question] standalone 5.7 version or how to update for e107 CMS

### ISSUE THREAD

**Issue by Jimmi08** [tltneon/lgsl#19]
Hello,
at first, thank you for all your job with maintaining this. 

I was asked to update e107 plugin by the same author (only e107 stuff, not LGSL). But the last version is for LGSL 5.7 and there were changes against 5.8.  

I would like to use 5.10.3 directly, but I don't know what are differences against SA version in lgsl code.  (e107 stuff is no problem)

For now I found only `$lgsl_config['cms'] `

I thought if I compare LGSL 5.7 SA vs e107 lgsl_files, that I could check this. 

Can somebody share this version? Or confirm that that cms config is the only difference?

Thank you

**Comment by tltneon** [comment]
Hello! I'm glad a lot by your words.

To upgrade lgsl 5.7 you should backup your current files and to replace with this ones: lgsl_class.php, lgsl_protocol.php, lgsl_admin.php
Also add new folder languages, styles and scripts. And in the end you need to add a few new lines in lgsl_config.php

Honestly, I didn't do that but LGSL 5.10.3 mostly should be compatible with older version.

**Comment by Jimmi08** [comment]
@tltneon
 You are right and I decided on a different approach. I use directly 5.10.3 version, no upgrade process and I created (in progress) new e107 files. For now, everything works and it is clear.  In testing phase now. 
I have issues only with userbar.php (but it doesn't work with SA version either), but it can be set it off. No priority.

**Comment by Jimmi08** [comment]
@tltneon 
great work really, it worked out of the box. Without you, this plugin will be lost.  

I will publish code after they will end with testing. They can compare with SA version, so they know if it worked before or not.
 
![image](https://user-images.githubusercontent.com/5429548/87186313-94562c80-c2eb-11ea-832c-cedc08d8162f.png)

I just added config to the admin area to avoid manual changing config file (they have 12 zones)

![image](https://user-images.githubusercontent.com/5429548/87186380-b3ed5500-c2eb-11ea-8385-91632061f7f9.png)

![image](https://user-images.githubusercontent.com/5429548/87186702-3c6bf580-c2ec-11ea-9f48-b3a42b987c50.png)

Frontend with darken style:

![image](https://user-images.githubusercontent.com/5429548/87186481-dbdcb880-c2eb-11ea-9958-49d60d35861f.png)

**Comment by tltneon** [comment]
I almost forgot to say you that you made awesome e107 plugin! Good job
