### ISSUE TITLE
Issue with SAMP $buffer->show() should not be there ?

### ISSUE THREAD

**Issue by wohahobg** [tltneon/lgsl#194]
Hello again :D

On line https://github.com/tltneon/lgsl/blob/lgsl7/src/lgsl_protocol.php#L1727 there is $buffer->show() that shows "details" and it does not return valid array.

Is good if we have option to enabled/disable that.

**Comment by tltneon** [comment]
Hi, @wohahobg 
Yeah, it shoundn't be there :D
Thanks!
