### ISSUE TITLE
Can you add Vintage Story

### ISSUE THREAD

**Issue by GameAreaCZ** [tltneon/lgsl#201]
To the server list?

**Comment by BaxAndrei** [comment]
It would be very useful and helpful if you could provide some documentation links for the server as well as any other links that would help with determining the protocols and queries for the server.

**Comment by GameAreaCZ** [comment]
Here are official docs for hosting the server

https://www.vintagestory.at/selfhosting/

**Comment by tltneon** [comment]
Hi @GameAreaCZ 
I looked at this game and no opened protocols found. So I tried to take at least something -> game server gives only its name, gamemodes and some settings
![image](https://github.com/tltneon/lgsl/assets/2452201/7ca41d47-fd3b-4fa8-9409-7b9b2f4df4e6)

**Comment by tltneon** [comment]
Done
