### ISSUE TITLE
[Feature request] 7 day graph

### ISSUE THREAD

**Issue by GameAreaCZ** [tltneon/lgsl#202]
Hello, the 1 day graph of players is so nice feature, but can you also add a 7 day graph of online players with days on the X axis?

**Comment by tltneon** [comment]
Hi @GameAreaCZ
Now you can freely set any count of hours in config.php. For example `$lgsl_config['history_hours'] = 24 * 7;`

**Comment by GameAreaCZ** [comment]
Can I use it for version 6 also? Or is it only version 7 compatible?

**Comment by GameAreaCZ** [comment]
Thank you, I switches to v7 because of that, but v7 is not so ready to production I'm starting to see. Anyway, thank you and good job.

**Comment by BaxAndrei** [comment]
I am not sure if it is a bug on v7 but my chart always have only one element on it. Always resets
