### ISSUE TITLE
[v7 RC] Game mode is showing "none" for game mode 0 on Urban Terror servers

### ISSUE THREAD

**Issue by UG-Asger** [tltneon/lgsl#211]
Would recommend to convert the responding number to text for game modes as below for Urban Terror (for 1-11 it is showing the correct number):

        "0": "Free for All",
        "1": "Last Man Standing",
        "3": "Team Deathmatch",
        "4": "Team Survivor",
        "5": "Follow the Leader",
        "6": "Capture and Hold",
        "7": "Capture the Flag",
        "8": "Bomb Mode",
        "9": "Jump",
        "10": "Freeze Tag",
        "11": "Gun Game"

**Comment by UG-Asger** [comment]
![image](https://github.com/user-attachments/assets/262737bb-f572-4529-8244-73a06e5e641b)

**Comment by tltneon** [comment]
Done
