### ISSUE TITLE
[v7 RC] Needs some updates for AQtion Quake 2

### ISSUE THREAD

**Issue by UG-Asger** [tltneon/lgsl#216]
Seems LGSL do not show maxclients and game mode (and maybe others) correctly after the new update to AQtion Quake 2 available on Steam
![image](https://github.com/user-attachments/assets/1d238a8e-e4ec-458d-b93b-d7f4da277870)

Yoy can check here: https://urbangamers.dk/lgsl7/

**Comment by tltneon** [comment]
Done
