### ISSUE TITLE
Problems with Location and Password

### ISSUE THREAD

**Issue by wG-Asger** [tltneon/lgsl#23]
Hi 

Location for NL Netherlands not displayed.
Icon for server with password not displayed (Urban Terror "g_needpass 1") 

![image](https://user-images.githubusercontent.com/68121399/92302659-238b6380-ef6e-11ea-81a1-7f749521db0a.png)
![image](https://user-images.githubusercontent.com/68121399/92302679-4453b900-ef6e-11ea-806d-76e51eaa0731.png)

**Comment by tltneon** [comment]
Hi

Got it! Ill fix that soon 👌

**Comment by wG-Asger** [comment]
Location for NL Netherlands still not working for me :(

Icon for password is fixed, though :)
![image](https://user-images.githubusercontent.com/68121399/92604717-1d202300-f2b1-11ea-95c5-2134af27be5f.png)

**Comment by tltneon** [comment]
To refresh location - use "Save - Clear cache" button in admin panel.

**Comment by wG-Asger** [comment]
Didn't think of that :) You are absolutely right, it works now. Thanks for your help :)

**Comment by tltneon** [comment]
You are welcome :+1:

**Comment by wG-Asger** [comment]
The e107 plugin looks pretty cool now. I extracted all the map levelshots in original size from Urban Terror. The image quality is much better now, since the are down scaled from much higher resolution:
![image](https://user-images.githubusercontent.com/68121399/92648428-afdcb400-f2e9-11ea-910a-04cd53fef200.png)
![image](https://user-images.githubusercontent.com/68121399/92648537-d995db00-f2e9-11ea-957a-22a7684dc841.png)
Thanks again for your support :)

**Comment by tltneon** [comment]
Wow! Looks awesome!

That's the good reason to make LGSL better :)

**Comment by wG-Asger** [comment]
Feel free to use screenshots to promote the e107 plugin  if you like :) https://wastedgoats.com/LGSL/

**Comment by wG-Asger** [comment]
I can see that you have used my old UG clan server in tour screen shot
![image](https://user-images.githubusercontent.com/68121399/92654858-c20e2080-f2f0-11ea-90c5-e248ed72d3ba.png)

**Comment by wG-Asger** [comment]
Made a few changes to make the mobile version match the theme on the web site:
![1](https://user-images.githubusercontent.com/68121399/92655075-216c3080-f2f1-11ea-915b-d6e244f0f479.jpg)

**Comment by tltneon** [comment]
I appreciate for your proposed. Next time I will use your website as a nice sample of LGSL look!

Time to time I was searching for sites who uses LGSL and I thought to add servers to main images :)

Mobile version is good enough. Thinking map isn.t so necessary to view on mobile devices?

**Comment by wG-Asger** [comment]
No, not for e107, because all the servers are listed below with map images if you scroll down. Not sure how it works for SA users, but screen gets cramped up easily on mobile.

**Comment by wG-Asger** [comment]
Jimmi did a really good job implementing the SA version to an e107 plugin :)
