### ISSUE TITLE
Image scalling/crop issue in Server detailed wiew

### ISSUE THREAD

**Issue by wG-Asger** [tltneon/lgsl#24]
Hi

When map image is square the bottom is cropped 

![image](https://user-images.githubusercontent.com/68121399/92302764-f25f6300-ef6e-11ea-91c6-e09cd4cee30d.png)

**Comment by wG-Asger** [comment]
In Zone view it works as expected

![image](https://user-images.githubusercontent.com/68121399/92302820-639f1600-ef6f-11ea-8013-1aa05b445d42.png)

**Comment by tltneon** [comment]
This is causing your image has 140x140px resolution.
**Better is using 250x180**px or you may find

`.details_info_column:nth-child(2), .details_password_image {
    background-size: cover;
    width: 250px;
    height: 188px;
}`

at file **lgsl/lgsl_files/styles/darken_style.css** and replace with

`.details_info_column:nth-child(2), .details_password_image {
    background-size: cover;
    width: 250px;
    height: 188px;
    background-position: center;
}`

**Comment by wG-Asger** [comment]
Hi. I really don't wanna change hundreds of map images ;( 
The Center background solution is fine for me. Thanks for your help :)
