### ISSUE TITLE
LGSL_PATH_PROBLEM

### ISSUE THREAD

**Issue by AleksandrPe** [tltneon/lgsl#32]
Hello, please tell me why half of the elements on the web page on my VDS have path problems?\
Below is one example.

style="background-image: url(/#LGSL_PATH_PROBLEM#/var/www/site.ru/home#/var/www/site.ru/servers/lgsl_files#/other/map_no_response.jpg);"

**Comment by tltneon** [comment]
Hello!

In this case you should set **$lgsl_config['url_path'] = "/var/www/site.ru/servers/lgsl_files;**" into your **lgsl_config.php** cause LGSL can't properly define folder location.

**Comment by AleksandrPe** [comment]
Thanks a lot, it helped me)
