### ISSUE TITLE
Problem with Iframe

### ISSUE THREAD

**Issue by arkancide** [tltneon/lgsl#33]
Hi Tltneon,
First of all, thank you for this code. I've been looking for a game server list for a long time. Openscource is still the best. Since there is no plug-in for Wordpress, I integrated LGSL as an iframe. But now I have a problem: the page navigation in the iframe refers to the parent page with "To Main Page". Is there a way to remove "To Main Page"? ()My site: https://www.w00tgames.de/gameserver/)
Thank you for your help
Arkancide

**Comment by tltneon** [comment]
Hi arkancide,
Easiest way to remove "To Main Page" is to make change in style.
Add this line in the end of file **/lgsl_files/styles/ogp_style.css**
`#topmenu > li:first-child {
  display: none;
}`

And thanks for using LGSL!

**Comment by arkancide** [comment]
Hi neon,
thank you for your help. Works fine.
greetings
Arkancide

**Comment by CoZmicShReddeR** [comment]
Hello thanks for keeping my favorite Game Server monitor from extinction. I have a similar request but I am using zones with Xenforo front page CMS addon with Widgets and I want remove the hyperlink from the map image 
https://www.cozworld.com/

Thanks! ;) 

Please keep up the amazing work!

**Comment by tltneon** [comment]
Hello @CoZmicShReddeR 

You can easily do this by removing line 90 and line 85 from file **lgsl_files/lgsl_zone.php** https://github.com/tltneon/lgsl/blob/master/lgsl_files/lgsl_zone.php#L90

**Comment by CoZmicShReddeR** [comment]
> Hello @CoZmicShReddeR
> 
> You can easily do this by removing line 90 and line 85 from file **lgsl_files/lgsl_zone.php** https://github.com/tltneon/lgsl/blob/master/lgsl_files/lgsl_zone.php#L90

Thank you, worked perfectly! ;)

**Comment by maxXx1** [comment]
> Hi arkancide, Easiest way to remove "To Main Page" is to make change in style. Add this line in the end of file **/lgsl_files/styles/ogp_style.css** `#topmenu > li:first-child { display: none; }`
> 
> And thanks for using LGSL!

This does not work for me :(
