### ISSUE TITLE
Add custom hyperlinks buttons?

### ISSUE THREAD

**Issue by mixxedxyz** [tltneon/lgsl#35]
Hello,
first of all i have tested this and works very great 👍 
this is by far the best open source serverlist that a server owner can have. 

im currently using the theme: ogp_style.css
and i would like to add on the top of the website on the center something like this: https://ibb.co/hM7Dnq7
would be cool if you can help me. 
👍 

i have tried to PM you on github to share paypal me link since i removed the credits from the website and i would like to donate for this. do you have discord or so where we can exchange the more private details?

**Comment by tltneon** [comment]
Hello!
Thanks for your words! I'm upgrading LGSL and Richard made awesome basis of LGSL.

To add something to the top center of website you need to edit 2 files.
**ogp_style.css**
Find:
`#topmenu {padding: 1em;background-color: #0000002b;border-bottom: 2px dashed black;}`
Replace:
`#topmenu {
  padding: 1em;
  background-color: #0000002b;
  border-bottom: 2px dashed black;
  text-align: center;
}`
If you want to add red border around links, remove lines 38 and 39 and add line below:
`#topmenu > li {
  display: inline-block;
  padding: 5px 10px;
  border-radius: 6px;
  border: 3px solid red;
}`

**index.php**
Find:
`<div id="topmenu">`
Add below something like:
`<li><a href="google.com">My link 1</a></li>`
`<li><a href="facebook.com">My link 2</a></li>`


I'm only have a Patreon page for donations.
