### ISSUE TITLE
New Game Icons

### ISSUE THREAD

**Issue by gdavey** [tltneon/lgsl#4]
Hey,

Sorry to be a pain I have tested LGSL and i must say it works amazingly, We currently run a 7d2d space engineers and Multiple ark Survival servers how would I go about changing the icons for these rather than it using the default Half life icon ?

They all use the Source engine if that helps ?

**Comment by gdavey** [comment]
Does not matter I found a way around it :)

**Comment by tltneon** [comment]
You may help to improve LGSL and make pull request with missing icons.

**Comment by gdavey** [comment]
hi tltneon thanks for the response I changed your code around thou to ensure I can show the game icons. It would not work before.
