### ISSUE TITLE
Problème Left4Dead 2

### ISSUE THREAD

**Issue by Sebbabas** [tltneon/lgsl#47]
Hello,
Following an update of Lefd4Dead2, I no longer have server info, this is normal.
Thank you .

https://zupimages.net/viewer.php?id=21/24/m25r.png

**Comment by tltneon** [comment]
Hello @Sebbabas !
Can you upload your image to somewhere else? I can't open it.
Or you may leave your website link here.

**Comment by Sebbabas** [comment]
Hello,
https://srv.gmus.fr/listserver
https://srv.gmus.fr/captures/L4D2.PNG

Thank you .

**Comment by tltneon** [comment]
@Sebbabas I just finished review of this issue...
There is not an update problem, I just tested on LGSL 5.9.6 and LGSL 6.0.1 - no server info.
I found and fixed new Steam
