### ISSUE TITLE
Graph Chart

### ISSUE THREAD

**Issue by Sebbabas** [tltneon/lgsl#48]
Hello,
I am in the process of testing the graph and I notice a discrepancy in the number of players.
Thank you

https://srv.gmus.fr/stat_1
https://srv.gmus.fr/stat_6

![Graph](https://user-images.githubusercontent.com/86149777/122781801-755c6a80-d2b0-11eb-9104-e17b0eb902a1.PNG)

**Comment by tltneon** [comment]
Hello @Sebbabas,
Actually, floating point numbers are used here. It is rounded for a nice look.
![](https://i.imgur.com/1zlBqLn.png)
You may replace line 60 into charts.php with `imagestring($im, 1, 3, ($maxY-$yStep*$i)-3, ($i * round($yStep/$scaleY, 2)), $black);` to showing numbers as on image.

**Comment by Sebbabas** [comment]
Hello
Wouldn't it be easier to make one line per slot (up to 32 for example) and then divide by 2 if higher?
Thank you

**Comment by tltneon** [comment]
Hello,
I made an overview for various players count:

![](https://imgur.com/bRugR4p.png)
![](https://imgur.com/VaZF4PC.png)
![](https://imgur.com/JOMYdYc.png)
![](https://imgur.com/w5VI00z.png)
Is that you said about?

**Comment by Sebbabas** [comment]
Hello
Yes that's exactly it.
The first image would be perfect.
Then I think that above 32 places you divide by 2, so a row is equal to 2 slots to one.
Thank you

**Comment by tltneon** [comment]
I tried to draw graph and if players' count above 32 with dividing by 2 so graph become messy for some servers like Discord, SA:MP, Rust which can has 300+ players.

**Comment by Sebbabas** [comment]
Hello
I put the modifications online and for my part it suits my request perfectly.
Thank you so much.
👍🤩
https://srv.gmus.fr/stat_1
https://srv.gmus.fr/stat_6

**Comment by tltneon** [comment]
Glad to hear it :)
