### ISSUE TITLE
v6.10 no map pic sidebar issue

### ISSUE THREAD

**Issue by CoZmicShReddeR** [tltneon/lgsl#51]
Hello, for the Sidebar I see No map pics or placement showing since I upgraded from v6.0.1 to v6.1.0

I see the map pics fine in the server list view just not showing in the widget sidebars

Sidebars
https://www.cozworld.com/

LGSL Server list
https://www.cozworld.com/pages/servers/

**Comment by tltneon** [comment]
Hello, @CoZmicShReddeR !
I just tested with v6.1.0 and images showing on my demo LGSL (on the bottom of page http://lgsl-demo.freesite.vip)
As I see, you using widgets not right from lgsl_zone.php (e.g. cozworld_sven_servers.php), may be there is a issue when some code updated.
Can show me your code or find some PHP errors?

**Comment by CoZmicShReddeR** [comment]
global $lgsl_zone_number, $output;
$lgsl_zone_number = 6;
$output = "";
require "lgsl_files/lgsl_zone.php";
echo $output;

**Comment by CoZmicShReddeR** [comment]
<?php
header("Cache-Control: no-cache, no-store, must-revalidate"); // HTTP 1.1.
header("Pragma: no-cache"); // HTTP 1.0.
header("Expires: 0"); // Proxies.
$url1=$_SERVER['REQUEST_URI'];
global $lgsl_zone_number, $output;
$lgsl_zone_number = 6;
$output = "";
require "lgsl_files/lgsl_zone.php";
echo $output;

**Comment by CoZmicShReddeR** [comment]
header("Cache-Control: no-cache, no-store, must-revalidate"); // HTTP 1.1.
header("Pragma: no-cache"); // HTTP 1.0.
header("Expires: 0"); // Proxies.
$url1=$_SERVER['REQUEST_URI'];
//header("Refresh: 40; URL=$url1");
global $lgsl_zone_number, $output;
$lgsl_zone_number = 6;
$output = "";
require "lgsl_files/lgsl_zone.php";
echo $output;

**Comment by CoZmicShReddeR** [comment]
It starts with <?php

**Comment by tltneon** [comment]
I just tested with Release v6.1.0 and your code but it still shows images for me.
When I looking on your website I have no found some lines of code
This is how it looks on your website:
![](https://imgur.com/69qnluW.png)
This is code that have to be there:
![](https://imgur.com/vdiRhw4.png)
You should check lgsl_zone.php for errors or mismatches.

I'll be waiting for your feedback

**Comment by CoZmicShReddeR** [comment]
Everything's good replaced with newer zone file
Odd I thought all files were replaced unless you recently modified it. ;)

**Comment by CoZmicShReddeR** [comment]
Thank you! ;)
