### ISSUE TITLE
Error userbar.php ?

### ISSUE THREAD

**Issue by Sebbabas** [tltneon/lgsl#57]
Hello
Missing parameters "$w" and "$color_map" in case of error of "$ _GET['s']" in the "userbar.php" line 21 to 25?
Thank you

**Comment by tltneon** [comment]
Hello @Sebbabas !
Thank you for your attention!
I'll fix this next update

**Comment by Sebbabas** [comment]
Hello @tltneon 
No problem, if that helps.
Thank you ;)
