### ISSUE TITLE
Request export IP´s to txt/php

### ISSUE THREAD

**Issue by DeadOnKeyboard** [tltneon/lgsl#6]
Hello tltneon,

I just have a little request and hope you can help me with it.

Is it possible to add a button to export ip's and ports to a txt or php file ?
for example what should be in the file.
ip:port
ip:port
ip:port
and so on 
it should be possible to save the file on the server, if possible in a user-defined location. 
would be very thankfully if you can do something like this. 

best regards

**Comment by tltneon** [comment]
Hello DeadOnKeyboard,

I made that feature simplest way.
You can use it, enter the admin panel, click on Advanced management and then click on Backup.
LGSLwill create a new file into /lgsl/ folder nearby admin.php

**Comment by DeadOnKeyboard** [comment]
Hello tltneon,

thanks a lot, works perfectly.
now i can use it as backup master server for an old fps game.

it is not necessary but is there a way to display the list by players and status ?
so that the servers with players are up and offline always down

best regards

**Comment by tltneon** [comment]
Hello DeadOnKeybard,

You can do it by changing one line in config.php:
Find **$lgsl_config['sort']['servers'] = "id";** nearby 30th line and
Replace to **$lgsl_config['sort']['servers'] = "players";**
            (or **$lgsl_config['sort']['servers'] = "status";**)

**Comment by DeadOnKeyboard** [comment]
yeah, I found that already, but if I switch to "player" 
The servers are sorted by population, but offline and empty servers are mixed.
When switching to "Status", offline servers are always shown at the end of the list, but empty and busy servers are mixed.

**Comment by tltneon** [comment]
Now it has to be working, try out latest commit and switch sorting type to "player".

**Comment by DeadOnKeyboard** [comment]
hmmm i have replaced the class.php and changed the sorting to player
but offline and online still mixed

**Comment by tltneon** [comment]
I'm trying to catch this bug but LGSL always sort after second page reloading and doens't mix at further reloads. And my bad - option must be set at "players", not "player"

**Comment by DeadOnKeyboard** [comment]
oh thx allot i will try ^^
