### ISSUE TITLE
No players info for new A2S_INFO

### ISSUE THREAD

**Issue by Accelerator74** [tltneon/lgsl#60]
For left 4 dead 2 servers (possibly other games), which recently switched to the new A2S_INFO, there is no information about the players (nickname, score and play time) in full info about server.

The problem arises because of this https://github.com/tltneon/lgsl/blob/master/lgsl_files/lgsl_protocol.php#L644. In the data array, in response to the request, there are 0 players for 0 element. However, element 1 and 2 contain the number of players. The old query had 4 elements, now 3, one of which for some reason is always 0.

At the moment, I temporarily did it like this
`if ($lgsl_need['p'] && $server['s']['players'][1] == "0") { $lgsl_need['p'] = FALSE; }`
but I don't think this is the correct fix.

**Comment by tltneon** [comment]
Hello @Accelerator74!
Can you show me screenshots of this cases?

I know about [new A2S_INFO](https://developer.valvesoftware.com/wiki/Server_queries#A2S_INFO) and some time ago it was fixed #47
Also I tested it with various servers:
![image](https://user-images.githubusercontent.com/2452201/128002201-09c78db7-971f-4c4c-abb0-848ddb7fbab6.png)
And one of server details:
![image](https://user-images.githubusercontent.com/2452201/128002444-5fb585b0-0f81-4df4-9079-34cd8f2fd7a7.png)
![image](https://user-images.githubusercontent.com/2452201/128002523-4c59f1be-5f24-48fa-87ec-2100726c0796.png)

**Comment by Accelerator74** [comment]
These servers use the old steamclient (replaced the original one). Try to scan the server: 94.103.88.131:27015

**Comment by tltneon** [comment]
L4D2 may not to send players details with first query. But anyway does it:
![image](https://user-images.githubusercontent.com/2452201/128009868-a6b58e75-dec9-4ec1-91af-afece0c4b08a.png)

**Comment by Accelerator74** [comment]
I have corrected the server address to be checked - 46.174.52.15:27255 :) It definitely cannot be scanned. I will send you a screenshot when my web host resumes my site ...

**Comment by Accelerator74** [comment]
![noplayers](https://user-images.githubusercontent.com/18032476/128016587-0b760868-4539-4424-a454-9118c31ac0c6.png)

**Comment by tltneon** [comment]
Now scanning process goes correctly
![image](https://user-images.githubusercontent.com/2452201/128163102-825f2c90-2b98-4b29-b558-beff8fa1850e.png)

**Comment by Accelerator74** [comment]
Yes, but it broke queries for servers, that use the old protocol :)
For example:
-1 / 25
![null](https://user-images.githubusercontent.com/18032476/128165778-acbddb0a-f76f-424a-bb85-967bbcbaf865.png)

**Comment by tltneon** [comment]
Meh, stupid case xD
I forgot checking whether already packet with main info is come

**Comment by Accelerator74** [comment]
Now when the server on the old protocol is empty, monitoring shows the number of players `-1` 😄
