### ISSUE TITLE
query for teaspeak.

### ISSUE THREAD

**Issue by Bebiano86** [tltneon/lgsl#61]
good afternoon I would like to have protocol for teaspeak.
thanks
Site: https://teaspeak.de/

**Comment by tltneon** [comment]
Hello @Bebiano86 !
No problem!
Where I can find any API docs or devs contact?

**Comment by Bebiano86** [comment]
Hi @tltneon .
I think the best way is to contact the dev on their forum.
https://forum.teaspeak.de/index.php?members/wolverindev.1/
