### ISSUE TITLE
query for Satisfactory.

### ISSUE THREAD

**Issue by Sebbabas** [tltneon/lgsl#69]
Hello,
Would it be possible to add the Satisfactory Game?
Thank you .

**Comment by tltneon** [comment]
Hello @Sebbabas!

Can you give me any server IP for testing queries?

**Comment by Sebbabas** [comment]
Hello,
IP = 163.172.80.245b ,
ServerQueryPort = 15777,
BeaconPort = 15000,
Port = 7777,
Thank you .

**Comment by tltneon** [comment]
Hello @Sebbabas 
I tried to find any info about it but nothing. So I only can add query with online status and server's version

**Comment by Sebbabas** [comment]
Hello @tltneon
Happy new year and health.
If you can already add the online status and the version of the server, it is already very good.
Thank you
