### ISSUE TITLE
Feed System

### ISSUE THREAD

**Issue by DeadOnKeyboard** [tltneon/lgsl#7]
Hello im again :)

Since greycube website is down maybe you can help me or explain me the feed system ?

If I understand it correctly, it automatically adds servers to the list when they send a request
to the feed link ?

Its an old gamespy game and i know how to change the gameserverfiles to another master server.
the game sends requests thrue fsockopen.

best regards

**Comment by tltneon** [comment]
Hello DeadOnKeyboard,

As I tested that code, it working as proxy.
Useful at situations when your server can't querying gameservers' data directly, and you connect by feed system to other website so it returning required infos.

But main trouble is when you requesting data LGSL throw to you error if you have gameservers that another 'masterserver' hasn't. So you need to syncing it mannually for a now.

**Comment by DeadOnKeyboard** [comment]
ah ok i understand.
thanks for the explanation
