### ISSUE TITLE
Query for more Games 

### ISSUE THREAD

**Issue by wahke** [tltneon/lgsl#72]
Maybe you can add this Games :

Call of Duty: Black Ops 3
Call of Duty: Modern Warfare 3
Call of Duty 3 (2006)
Call of Duty: Modern Warfare 2
Crysis 2
DayZ
DayZ Mod
Far Cry 2
Halo 2
James Bond 007: Nightfire
Mafia II - Multiplayer
Mafia II - Online
Minecraft: Bedrock Edition

Thank You Verry Much

**Comment by tltneon** [comment]
Unfortunately, I'm nothing to found about some games like Call of Duty 3 (2006) or Far Cry 2 or James Bond 007: Nightfire. I'll add  Mafia II - Multiplayer soon. Other games already can be queried (Call of Duty: Modern Warfare 3, DayZ, DayZ Mod, Minecraft: Bedrock Edition)

**Comment by tltneon** [comment]
Also added Call of Duty IW protocol for CoD: MW2, MW3, Ghosts
