### ISSUE TITLE
Any feedback about security issues 

### ISSUE THREAD

**Issue by amammad** [tltneon/lgsl#73]
Hey LGSL team 
I was reported some security issues in Huntr.dev and after near three months I don't see any feedback from you

Please If you accept the validity of the reports just click on the validate submit button on Huntr.dev to able me to get my bounty from Huntr.dev 

Best regards, Amammad.

**Comment by tltneon** [comment]
As I saw your report, there's no critical issues. Yes, it could be possible to lose data, but only if you passed by suspicious links. Meh

**Comment by amammad** [comment]
Can I ask you to validate my report to get my bounty, please?
After validation, you can submit a fix commit whenever you want.

**Comment by amammad** [comment]
I can change the severity to 3, is it possible to validate the reports?
