### ISSUE TITLE
Farming Simulator 17/19/22

### ISSUE THREAD

**Issue by Webby0815** [tltneon/lgsl#77]
Can you implate the Farming Simulator please

**Comment by Sebbabas** [comment]
Hello,
For farming, you must add a "code" column in the TABLE.
Create an XML function 'simplexml_load_string'. 
exemple : https://gmus.duckdns.org/listserver-d-MTM

thank.

**Comment by Webby0815** [comment]
?? i cant do this :-(

**Comment by Webby0815** [comment]
Can you Help me,in which File Mist i implate this

**Comment by Sebbabas** [comment]
Hi,
I add this code in 'lgsl_protocol.php' 'lgsl_protocol.php'
Please note that this works for me, but I am not a professional, please be indulgent.

after line 53 :
>"fs2013"		=> "Farming Simulator 2013",
"fs2015"		=> "Farming Simulator 15",
"fs2017"		=> "Farming Simulator 17",
"fs2019"		=> "Farming Simulator 19",
		
after line 184 :
>"fs2013"		=> "39",
"fs2015"		=> "39",
"fs2017"		=> "39",
"fs2019"		=> "39",
		
after line 3994 :
>
//------------------------------------------------------------------------------------------------------------+
//------------------------------------------------------------------------------------------------------------+
function lgsl_query_39(&$server, &$lgsl_need, &$lgsl_fp){	// Farming Simulator 13/15/17/19 | OK - 26/03/21
	$serverAddress = "http://{$server['b']['ip']}:{$server['b']['q_port']}/feed/dedicated-server-stats.xml?code={$server['b']['tmf_pass']}";
	$xml = getServerStatsSimpleXML($serverAddress,$server['b']['type'],$server['b']['q_port']);
	$key = array('Big Bud Pack','Platinum Expansion','KUHN Pack','ROPA Pack');	//	LIST DLC FS
	$m=0;
	if($xml){		
	if($xml["name"] != NULL){$server['s']['name'] = $xml["name"];}else{$server['s']['name'] = "WebInterface ON | Server OFF";}
	$server['b']['status'] = 1;
	$server['s']['map'] = $xml["mapName"];
	$server['s']['playersmax'] = $xml->Slots["capacity"];
	$server['s']['players'] = $xml->Slots["numUsed"];
	$server['s']['password'] = 0;
	$server['e']['Game'] = $xml["game"];
	$server['e']['Server'] = $xml["server"];
	$server['e']['dedicated'] = "Dedicated";
	$server['e']['Platform'] = "Wine";
	$server['e']['Version'] = $xml["version"];
	$server['e']['Heure_Carte'] = gmdate("H:i:s",($xml['dayTime']*1)/1000);
	foreach($xml->Mods->Mod as $mod){
		if(in_array($mod, $key )){$item_value = '-DLC- /';}else{$item_value = '';}
			$server['e']['Mods'] = isset($server['e']['Mods']) ? $server['e']['Mods'] : NULL;
			$m++; $server['e']['Mods'] .= $m ." | ".$mod." / ".$item_value." ".$mod["author"]." / ". $mod["version"]." <br/>";
	}
	$server['e']['Money'] = number_format($xml['money']+0, 0, '','.').' Euros';
	if ($xml->Slots["numUsed"] >= 1) {
		$slotCount = 1;
		foreach ($xml->Slots->Player as $player){
			if ($player["isUsed"] == "true") {
				$hours = floor($player["uptime"]/60);
				$minutes = floor($player["uptime"]-($hours*60));
				$server['p'][$slotCount]['name'] = $player;
				$server['p'][$slotCount]['Time'] = $hours . ":" . sprintf("%02d", $minutes) . "h ";
				$server['p'][$slotCount]['Adn'] = (($player["isAdmin"] == "true")?"Oui":"Non");
			}
			$slotCount++;
		}
	}else{$server['p'] = "";}
		return TRUE;
	}else{
		return FALSE;
	}
}
//------------------------------------------------------------------------------------------------------------+
//------------------------------------------------------------------------------------------------------------+

after line 3994 :
>
//---------------------------------------------//
//---Fonction Farming Simulator----------------//
function loadFileHTTPSocket($domain, $port, $path, $timeout) {
$fp = fsockopen($domain, $port, $errno, $errstr, $timeout);
if ($fp) {
// Make request
$out = "GET ". $path . " HTTP/1.0\r\n";
$out .= "Host: ". $domain . "\r\n";
$out .= "Connection: Close\r\n\r\n";
fwrite($fp, $out);
// Get response
$resp = "";
while (!feof($fp)){$resp .= fgets($fp, 256);}
fclose($fp);
// Check status is 200
if(preg_match("/HTTP\/1\.\d\s(\d+)/", $resp, $matches) && $matches[1] == 200) {
// Load xml as object
$parts = explode("\r\n\r\n", $resp);
$temp = "";
for ($i=1;$i<count($parts);$i++) {
$temp .= $parts[$i];
}
return $temp;
}
}
return false;
}
//-----
function getServerStatsSimpleXML($url,$type,$q_port) {
$urlParts = parse_url($url);
$cacheFile = ".cache/dedicated-server-stats-$type-$q_port.cached";
$cacheTimeout = 4*2;
if(file_exists($cacheFile) && filemtime($cacheFile) > (time() - ($cacheTimeout) + rand(0, 10))) {
$xmlStr = file_get_contents($cacheFile);
} else {
error_reporting(0);
$xmlStr = loadFileHTTPSocket($urlParts["host"], $urlParts["port"], $urlParts["path"] . "?" . $urlParts["query"], 4);
error_reporting(E_ALL);
if ($xmlStr) {
$fp = fopen($cacheFile, "w");
fwrite($fp, $xmlStr);
fclose($fp);
}
}
return simplexml_load_string($xmlStr);
}

**Comment by Webby0815** [comment]
Thanks , i would Test it later

**Comment by Webby0815** [comment]
give error 500

**Comment by Webby0815** [comment]
Parse error: syntax error, unexpected '1' (T_LNUMBER) in /var/www/clients/client1/web19/web/lgsl_files/lgsl_protocol.php on line 4022

this is the line $server['e']['Heure_Carte'] = gmdate("H:i:s",($xml['dayTime']1)/1000);

**Comment by Sebbabas** [comment]
Hello
you use the code for which farming simulator?

**Comment by Webby0815** [comment]
this code is not functionally , the xml api code was not implate in the code.... has you discord ?

**Comment by Sebbabas** [comment]
no I have no discord and I am French and do not speak English :(

**Comment by Webby0815** [comment]
YES , you must insert the ?code=**eaef1e92044c7441a46514773f074ec3** by registriatrion a server ...where is that form ? thas my problem :-(

**Comment by Sebbabas** [comment]
There,
It is this column 'code' that I added in the table after 's_port'.
Please note that another page must be modified afterwards.

**Comment by Webby0815** [comment]
yes ,thats row have a set , i need the files ,ikl. the add page :-(

**Comment by Sebbabas** [comment]
is the 'lgsl_add.php' page causing you a problem?

**Comment by Webby0815** [comment]
no , thats row : 

$server['e']['Heure_Carte'] = gmdate("H:i:s",($xml['dayTime']**1**)/1000);

i think the 1 iss the problem ... the error is delete , but how becam i the key form 
in the add page

**Comment by Sebbabas** [comment]
Yes 
it's 

> $server['e']['Heure_Carte'] = gmdate("H:i:s",($xml['dayTime']*1)/1000);

**Comment by Webby0815** [comment]
okay ,and the form for the api key code ?

**Comment by Sebbabas** [comment]
Page lgsl_add.php ?

**Comment by Webby0815** [comment]
yes ...

**Comment by Webby0815** [comment]
yes ....

**Comment by Webby0815** [comment]
more than 5 mins ;-)

**Comment by Sebbabas** [comment]
Sorry for the delay,
I modified all the files, I even advise you to do a reinstallation like that even the BDD will be Good. 

https://uptobox.com/1uxhiq63fwd8

**Comment by Webby0815** [comment]
this works half ;-/
look : https://g-tracker.de/index.php?s=21

**Comment by Sebbabas** [comment]
Hello
Since I don't have an fs22 server, I don't know how the xml file is constructed so that I can adapt the code.

**Comment by Webby0815** [comment]
no , the image stats dont works

**Comment by Sebbabas** [comment]
ok i'm looking at it now, i must have forgotten a file!

**Comment by Sebbabas** [comment]
Update : https://uptobox.com/uu8mjj2fsztt

Attention I noticed that if a port or g_code is at "0", the banner does not work.

**Comment by Webby0815** [comment]
good , now works the chats.php not :-(

**Comment by Sebbabas** [comment]
charts.php
line 43 replace : 
>$server = lgsl_query_cached($lookup['type'], $lookup['ip'], $lookup['c_port'], $lookup['q_port'], $lookup['s_port'], "s");

to :

>$server = lgsl_query_cached($lookup['type'], $lookup['ip'], $lookup['c_port'], $lookup['q_port'], $lookup['s_port'], $lookup['g_code'], "s");

**Comment by Webby0815** [comment]
Great , its works ! i wait for the chart updates ....big thanks to you

**Comment by Sebbabas** [comment]
lgsl_protocol.php
line 4029 replace : 
>if($type != 'fs2022'){

to :

>if($server['b']['type'] != 'fs2022'){

thank.

**Comment by Webby0815** [comment]
Cool ,thanks, 
can i do it , the uipdate only from rcon ,the page speed is not to fast

**Comment by Sebbabas** [comment]
Hello,
I use it and I have no problem.

**Comment by Webby0815** [comment]
https://g-tracker.de/ 
some servers show nothing and the page is a bit slow. I would like to update the whole thing via cron job

**Comment by Sebbabas** [comment]
Hello
lgsl_protocol.php
line 4092 replace :

  >$cacheTimeout = 4*2;

to :

>$cacheTimeout = 25*2;

bye.

**Comment by Webby0815** [comment]
the side is slowly , can i remove update per view @ index ...

**Comment by TacTicTow** [comment]
How did you add the player bargraph bubble in the list.php?
