### ISSUE TITLE
lgsl image mod

### ISSUE THREAD

**Issue by Yamiru** [tltneon/lgsl#8]
hello, i use your latest version of script
imagestatus not work :/
not work imagemod i trying to change direct_index, no_realpath, url_path and same problem :/

look at it 
thank you

> [url=https://servers.avaloncs.group/lgsl_files/../?s=15][img]https://servers.avaloncs.group/lgsl_files/../userbar.php?s=15[/img][/url]

**Comment by Yamiru** [comment]
i upload your new sversion, but link works but image not :/

https://servers.avaloncs.group/?s=15

**Comment by tltneon** [comment]
@Yamiru, as I see, you haven't necessary files such as **banner_thin.gif**, **verdana.ttf** into /other/ directory so php can't make banner. Also you can see php errors at webhost to recognize the reason

**Comment by Yamiru** [comment]
ok thank you works now ^^
