### ISSUE TITLE
Site

### ISSUE THREAD

**Issue by Webby0815** [tltneon/lgsl#92]
I have a problem. Sometimes it doesn't show the page correctly. Just like the overview page. Is that already known? I am sending a screenshot attached

https://g-tracker.de/1.jpg
https://g-tracker.de/2.jpg
https://g-tracker.de/3.jpg

**Comment by TacTicTow** [comment]
Youre missing this line #19 

$uri = $_SERVER['REQUEST_URI'];

Should be in your lgsl_list.php file. Either add that line or download the current php file and overwrite what is on your site.

**Comment by tltneon** [comment]
Duplicate https://github.com/tltneon/lgsl/discussions/76
