### ISSUE TITLE
Is this abanoned? 

### ISSUE THREAD

**Issue by TacTicTow** [tltneon/lgsl#93]
Battefield 3 does not seem to work. 

I would like to see a query for Black Ops 3, if possible.

The preview for mao images needs to be fixed.

Charts.php does not seem to work and I can find no documentation on setting it up or making it work. Does it need a cron job?

I have seen some edits where there is a player bargraph that fills on the list page. I cannot find any where online on how to do this. 

Does anyone have any help they can supply here? The author has not been around in some time.

Thanks!

**Comment by tltneon** [comment]
Hello @TacTicTow 
For now, I don't have enough of time but anyway try to improve LGSL in future. If you have any issues, better to send here any screenshots or error logs to help me understand why this happening and how to fix it.

charts.php works fine for me. But can fault if fonts doesn't exists in folder. Charts depends on query stats that saves then someone visit LGSL or you need to add cron job.

**Comment by TacTicTow** [comment]
Thank you so much for responding.  I do understand being busy!! :-)

I am still unable to get charts.php to work. I see it working on some sites but not all, so I know it is not just me. Not sure if I should start a separate issue for this. Here is my setup. 

Apache (latest) on a Windows box using Windows 2019

I verified the font was in the folder. 

I executed the command "php -q lgsl_cron.php" and got the following result:

<pre>STARTING [ TIME LIMIT: 3600 ] [ CACHE TIME: 60 ]

0.01    :callofdutybo2  :64.74.97.92                   :4980  :4980  :0
0.02    :valheim        :64.74.97.92                   :2456  :2457  :0
0.62    :rust           :64.74.97.92                   :28015 :28015 :0
0.65    :callofdutymw2  :64.74.97.92                   :28961 :28961 :0
0.66    :homefront      :64.74.97.92                   :27018 :27018 :0
0.76    :frontlines     :64.74.97.92                   :5476  :5478  :0
0.78    :remnants       :64.74.97.92                   :7779  :27019 :0
0.92    :7dtd           :64.74.97.92                   :26900 :26900 :0
1.06    :bfbc2          :64.74.97.92                   :19567 :48888 :0
1.07    :miscreated     :64.74.97.92                   :64090 :64092 :0
1.08    :holdfast       :64.74.97.92                   :20100 :27001 :0
1.65    :conanexiles    :64.74.97.92                   :7790  :27045 :0
2.17    :callofdutybo   :66.55.158.201                 :3074  :3074  :0
2.73    :frontlines     :64.97.97.92                   :7900  :7900  :0
3.23    :arkse          :64.74.97.92                   :7777  :27015 :0

FINISHED</pre>

I setup a task in the scheduler to run the following scripts every 30 mins...

php -q l lgsl_details.php
php -q l lgsl_list.php

Nothing is going on with my charts.php

https://saltybawls.com/lgsl/

If you wish to take a look.  Very odd. It looks as if everything should work.

Thank you again for all that you do.

**Comment by tltneon** [comment]
Executing "php -q lgsl_cron.php" should working I tested on my server
![image](https://user-images.githubusercontent.com/2452201/153249389-69e4660e-7767-4b78-a556-e889a61563fa.png)

You need to be sure that field `cache` in LGSL table (database) has `MEDIUMTEXT` type
![image](https://user-images.githubusercontent.com/2452201/153249787-5dbd0100-e37b-4103-a904-2689198f6fa4.png)

Other option - just purge cache to fill it again
![image](https://user-images.githubusercontent.com/2452201/153250252-370ec001-3ed1-47be-a0a8-958ce46fba8f.png)

As I see your making some code changes by yourself so that may be cause. Anyway, you might try clean install of LGSL

**Comment by TacTicTow** [comment]
So I took your advice and started over from scratch. I re-did all my edits and I was able to get my servers to work with the cron on my Linux website and using Task Scheduler on my Windows web server. Thank you for your help. What time frame for refresh do you recommend? My server refreshes pretty fast. I currently have it set to 15 min intervals.

Do you have a Paypal or Patreon account? I would like to send you some money for your help. It is nice to finally have it working!! 😊


I also responded to a discussion thread about adding the chart to the banner. I was going to ask you about doing it. I could eventually do it but my PHP skills are lacking. I think you could accomplish it much faster and I would be happy to donate more money to you for your time.  If you are interested, this is my line of thinking and how I planned to have my server banners appear. 

I do not use your static banner and have a banner for each game. So for example, this is my base banner for Black Ops that I planned to use with the chart. 



Once the server is queried it would impose the map image and server info like so….



This is how I am looking to set it up for my own use. You can create the banners for your script however you like. I am happy to send you money to help me get mine looking like this. I would prefer the chart to be dark so it matches the theme of my game banners. The color of the graph text and bar to be yellow. I would also like the final image to have the rounded corners. 

Interested? Can you help? 


Thanks again and please send me your link to however you accept donations.

**Comment by tltneon** [comment]
I'm recommend to set 15-45 mins for cron job.

I'm also made [Patreon](https://www.patreon.com/ru_neon) page but not sure what to add in it :)

And I could help you with your banner. Can you send me some example images?

**Comment by TacTicTow** [comment]
Got the banners working. Thank you.

Set my cron for 15 mins and that seems to work well. 

https://saltybawls.com/lgsl/?s=1

https://saltybawls.com/lgsl/userbar.php?s=1&t=2

I got to be your first patreon.  :)
