### ISSUE TITLE
LGSL in Laravel

### ISSUE THREAD

**Issue by grinjackal** [tltneon/lgsl#94]
Hello, 

I tryed LGSL (GameQ dont support discord and looks like dead project)  and its looks like, in Laravel 8/9 its not loading after all, even if i try include lgsl_class file..

So, im asking... Can be this somehow fix?

Regards, Grin.

**Comment by tltneon** [comment]
Hello @grinjackal 

I pretty sure that is not a good option (i don't know about Laravel at all) but it's worked for me

![image](https://user-images.githubusercontent.com/2452201/153755443-132dd1d1-8e64-48f8-9471-1221e78eac8a.png)


1. Place **lgsl** folder into **laravelapp/vendor**
2. Add something like that in **laravelapp/resources/views/**
```blade
@php
    include(base_path('vendor') . '/lgsl/lgsl_files/lgsl_class.php');
    $server = lgsl_query_live('urbanterror', '176.9.28.206', 27971, 27971, 0, "s");
@endphp
<div class="p-6 border-t border-gray-200 dark:border-gray-700 md:border-t-0 md:border-l">
    <div class="flex items-center">
        <div class="ml-4 text-lg leading-7 font-semibold">
            <a href="#" class="underline text-gray-900 dark:text-white">
                {{$server['s']['name']}}
            </a>
        </div>
    </div>

    <div class="ml-12">
        <div class="mt-2 text-gray-600 dark:text-gray-400 text-sm">
            IP: {{$server['b']['ip']}}:{{$server['b']['c_port']}}
        </div>
        <div class="mt-2 text-gray-600 dark:text-gray-400 text-sm">
            Type: {{$server['b']['type']}}
        </div>
        <div class="mt-2 text-gray-600 dark:text-gray-400 text-sm">
            Players: {{$server['s']['players']}}/{{$server['s']['playersmax']}}
        </div>
    </div>
</div>
```

**Comment by grinjackal** [comment]
Oh, You are using it in *.blade.php?

I was trying to use it in Controller (my FE is in React)....


I will try it again later, thabks for advice :D
